program: src/train_toxicity.py
method: grid
metric:
  name: validation/loss
  goal: minimize
parameters:
  base_model:
    values: ["xlm-roberta-large", "microsoft/mdeberta-v3-base", "bert-base-multilingual-cased", "microsoft/deberta-v3-large", "dbmdz/german-gpt2"]
  learning_rate:
    values: [1.0e-5, 5.0e-5, 0.9e-4, 1.0e-4, 2.0e-4, 3.0e-4]