program: src/train_toxicity_gbert.py
method: grid
metric:
  name: validation/loss
  goal: minimize
parameters:
  base_model:
    value: "deepset/gbert-base"
  learning_rate:
    values: [1e-4, 6e-5, 5e-6]