program: src/test_script.py
method: random
metric:
  name: validation_loss
  goal: minimize
parameters:
  model:
    values:
      [
        "Hate-speech-CNERG/dehatebert-mono-german_labels=2",
        "ankekat1000/toxic-bert-german",
        "jorgeortizv/BERT-hateSpeechRecognition-German",
        "xlm-roberta-large",
        "bert-base-german-cased",
      ]
  optimizer:
    value: "adam"
  learning_rate:
    min: 1.0e-5
    max: 1.0e-2
  epochs:
    value: 5
