program: src/train_toxicity_baseline.py
method: random
metric:
  name: validation/loss
  goal: minimize
parameters:
  base_model:
    values:
      [
        "ankekat1000/toxic-bert-german",
        # "jorgeortizv/BERT-hateSpeechRecognition-German",
        "dbmdz/bert-base-german-uncased",
        # "Hate-speech-CNERG/dehatebert-mono-german_labels=2",
        # "xlm-roberta-large",
      ]
  optimizer:
    value: "adam"
  learning_rate:
    min: 5.0e-5
    max: 1.0e-3
  epochs:
    value: 5
