program: src/train_toxicity.py
method: grid
metric:
  name: validation/loss
  goal: minimize
parameters:
  base_model:
    values: ["xlm-roberta-base"]
  learning_rate:
    values: [5.0e-5, 1.0e-4, 2.0e-4]