task: "hate_speech_unified"
class_names: ["non_hate_speech", "hate_speech"]

beta1: 0.9
beta2: 0.999

model: "hate-speech-unified"

epochs: 5

warmup_ratio: 0.1
weight_decay: 0.1

hidden_dropout_prob: 0.1

early_stopping_enabled: False