program: src/train_targeted_baseline.py
method: grid
metric:
  name: validation_loss
  goal: minimize
parameters:
  model:
    values:
      "xlm-roberta-large"
  optimizer:
    value: "adam"
  learning_rate:
    min: 0.0001
    max: 0.1
  epochs:
    value: [10, 15]
