program: src/train_targeted_baseline.py
method: grid
metric:
  name: validation_loss
  goal: minimize
parameters:
  model:
    value:
      "xlm-roberta-large"
  optimizer:
    value: "adam"
  learning_rate:
    values: [0.001, 0.001]
  epochs:
    values: [10, 15]
