# DATA
train_data: "data/processed_training_main_v4.csv"
evaluation_data: ["data/processed_evaluation_expert_v4.csv", "data/processed_evaluation_representative_v4.csv", "data/processed_evaluation_main_v4.csv"]
evaluation_data_names: ["expert", "representative", "main"]
dataset_portion: 1
transform_lowercase: False
transform_remove_umlauts: False
transform_clean: True

# OPTIMIZER
optimizer: "adamw"
use_learning_rate_finder: False

# MODEL
model_directory: "/cluster/scratch/ewybitul/models"
mixed_precision: null
adapter_type: "default"

# TRAINING
seed: 42
validation_split: 0.1
batch_size: 16
create_checkpoints: True
checkpoint_period: 1

# EARLY STOPPING
early_stopping_enabled: False

# WANDB logging
logging_period: 1024
log_hardest_examples: ["evaluation"]
examples_to_log: 500
log_model_to_wandb: False

# LOSS
class_weight: "unchanged"
