# DATA
train_data: "data/processed_comments_train_v3.csv"
evaluation_data: "data/processed_comments_evaluation_v3.csv"
dataset_portion: 1
transform_lowercase: False
transform_remove_umlauts: False
transform_clean: True

# OPTIMIZER
optimizer: "adam"
use_learning_rate_finder: False
# learning_rate: 3.0e-5
# end_learning_rate: 0.1,
# learning_rate_finder_steps: 1000


# MODEL
model_directory: "./dsl_hate_speech/models"

# TRAINING
seed: 42
validation_split: 0.1
batch_size: 16
create_checkpoints: True
checkpoint_period: 1

# EARLY STOPPING
early_stopping_enabled: False


# WANDB logging
logging_period: 512
log_hardest_examples: ["evaluation"]
examples_to_log: 100
log_model_to_wandb: False

# LOSS
class_weight: "unchanged"
